### ISSUE TITLE
Precision

### ISSUE THREAD

**Issue by natcl** [tedstriker/node-red-contrib-sequencer#1]
I want to record data coming over UDP that is sent quite fast (below one millisecond between packets) and I'd be curious to try using the [nanotimer](https://github.com/Krb686/nanotimer) library to gain more precision.  Would you eventually be interested by a pull request that would add that mode ?

**Comment by tedstriker** [comment]
As long as it's optional (for the user), clean coded, keeping other users implementation intact and not adding limitations I'm fine with it.

Despite that: What's your motivation to keep track of the UDP packets timing?

**Comment by tedstriker** [comment]
no response -> closing

**Comment by natcl** [comment]
Oops sorry for the late answer.
The motivation is to record OSC and Artnet packets which can sometimes arrive at intervals < 1ms
